#!/bin/bash

exec 2>>errors.txt

API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERRORS_FILE="errors.txt"

response=$(curl -Ss -w "%{http_code}" --fail "$API_URL" \
    -o tmp.json)

http_code="${response: -3}"

if [ "$http_code" -eq 200 ]; then
    mv tmp.json "$OUTPUT_FILE"
fi
