#!/bin/bash

pokemon_list=('bulbasaur' 'ivysaur' 'venusaur' 'charmander' 'charmeleon')
pokemon_data_dir="pokemon_data"

mkdir -p "$pokemon_data_dir"

for pokemon in "${pokemon_list[@]}"; do
    echo "Fetching data for $pokemon..."

    API_URL="https://pokeapi.co/api/v2/pokemon/$pokemon"
    OUTPUT_FILE="${pokemon_data_dir}/${pokemon}.json"
    ERRORS_FILE="errors.txt"

    attempt=1
    success=false

    while [ $attempt -le 3 ]; do
        error_message==$(curl -Ss --fail "$API_URL" -o "$OUTPUT_FILE" 2>&1)

        if [ $? -eq 0 ]; then
            echo "Saved data to $OUTPUT_FILE. ✅"
            success=true
            break
        else
            echo "Attempt $attempt for $pokemon failed. Retrying..."
            sleep 2
        fi

        ((attempt++))
    done

    if [ "$success" = false ]; then
        echo "[$pokemon] $error_message" >> "$ERRORS_FILE"
    fi

    sleep 2 # Wait before the next request
done
