#!/bin/bash
SOURCE_FILE="data.json"

# Extract required data from JSON
NAME=$(jq -r '.name' "$SOURCE_FILE")
TYPE=$(jq -r '.types[0].type.name' "$SOURCE_FILE")
HEIGHT=$(jq -r '.height' "$SOURCE_FILE")
WEIGHT=$(jq -r '.weight' "$SOURCE_FILE")

# Capitalize name and type
name=$(echo "$NAME" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
type=$(echo "$TYPE" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

# Convert height and weight to appropriate units
formatted_height=$(echo "$HEIGHT" | awk '{print $1/10}')
formatted_weight=$(echo "$WEIGHT" | awk '{print $1/10}')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
